services:
  - type: web
    name: stockplayer
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false
      - key: NEWSAPI_KEY
        sync: false
